Search.appendIndex(
    [
                {
            "fqsen": "\\deleteGroupItem\u0028\u0029",
            "name": "deleteGroupItem",
            "summary": "",
            "url": "namespaces/default.html#function_deleteGroupItem"
        },                {
            "fqsen": "\\editUserAccount\u0028\u0029",
            "name": "editUserAccount",
            "summary": "",
            "url": "namespaces/default.html#function_editUserAccount"
        },                {
            "fqsen": "\\editUserAccountRole\u0028\u0029",
            "name": "editUserAccountRole",
            "summary": "",
            "url": "namespaces/default.html#function_editUserAccountRole"
        },                {
            "fqsen": "\\delete_user\u0028\u0029",
            "name": "delete_user",
            "summary": "",
            "url": "namespaces/default.html#function_delete_user"
        },                {
            "fqsen": "\\getPendingUsers\u0028\u0029",
            "name": "getPendingUsers",
            "summary": "",
            "url": "namespaces/default.html#function_getPendingUsers"
        },                {
            "fqsen": "\\getPendingUsersReadOnly\u0028\u0029",
            "name": "getPendingUsersReadOnly",
            "summary": "",
            "url": "namespaces/default.html#function_getPendingUsersReadOnly"
        },                {
            "fqsen": "\\getRole\u0028\u0029",
            "name": "getRole",
            "summary": "",
            "url": "namespaces/default.html#function_getRole"
        },                {
            "fqsen": "\\_getRole\u0028\u0029",
            "name": "_getRole",
            "summary": "",
            "url": "namespaces/default.html#function__getRole"
        },                {
            "fqsen": "\\getUserGroups\u0028\u0029",
            "name": "getUserGroups",
            "summary": "",
            "url": "namespaces/default.html#function_getUserGroups"
        },                {
            "fqsen": "\\getUserGroupsApproved\u0028\u0029",
            "name": "getUserGroupsApproved",
            "summary": "",
            "url": "namespaces/default.html#function_getUserGroupsApproved"
        },                {
            "fqsen": "\\approveUser\u0028\u0029",
            "name": "approveUser",
            "summary": "",
            "url": "namespaces/default.html#function_approveUser"
        },                {
            "fqsen": "\\rejectUser\u0028\u0029",
            "name": "rejectUser",
            "summary": "",
            "url": "namespaces/default.html#function_rejectUser"
        },                {
            "fqsen": "\\getGroupCount\u0028\u0029",
            "name": "getGroupCount",
            "summary": "",
            "url": "namespaces/default.html#function_getGroupCount"
        },                {
            "fqsen": "\\getGroupName\u0028\u0029",
            "name": "getGroupName",
            "summary": "",
            "url": "namespaces/default.html#function_getGroupName"
        },                {
            "fqsen": "\\getUsers\u0028\u0029",
            "name": "getUsers",
            "summary": "",
            "url": "namespaces/default.html#function_getUsers"
        },                {
            "fqsen": "\\suspendUser\u0028\u0029",
            "name": "suspendUser",
            "summary": "",
            "url": "namespaces/default.html#function_suspendUser"
        },                {
            "fqsen": "\\suspendUserWithReason\u0028\u0029",
            "name": "suspendUserWithReason",
            "summary": "",
            "url": "namespaces/default.html#function_suspendUserWithReason"
        },                {
            "fqsen": "\\reactivateUser\u0028\u0029",
            "name": "reactivateUser",
            "summary": "",
            "url": "namespaces/default.html#function_reactivateUser"
        },                {
            "fqsen": "\\getUserDetails\u0028\u0029",
            "name": "getUserDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getUserDetails"
        },                {
            "fqsen": "\\getUserID\u0028\u0029",
            "name": "getUserID",
            "summary": "",
            "url": "namespaces/default.html#function_getUserID"
        },                {
            "fqsen": "\\getUserGroupsEditor\u0028\u0029",
            "name": "getUserGroupsEditor",
            "summary": "",
            "url": "namespaces/default.html#function_getUserGroupsEditor"
        },                {
            "fqsen": "\\getCodes\u0028\u0029",
            "name": "getCodes",
            "summary": "",
            "url": "namespaces/default.html#function_getCodes"
        },                {
            "fqsen": "\\getCallHistory\u0028\u0029",
            "name": "getCallHistory",
            "summary": "",
            "url": "namespaces/default.html#function_getCallHistory"
        },                {
            "fqsen": "\\delete_callhistory\u0028\u0029",
            "name": "delete_callhistory",
            "summary": "",
            "url": "namespaces/default.html#function_delete_callhistory"
        },                {
            "fqsen": "\\changeUserPassword\u0028\u0029",
            "name": "changeUserPassword",
            "summary": "",
            "url": "namespaces/default.html#function_changeUserPassword"
        },                {
            "fqsen": "\\getCivilianNamesOwn\u0028\u0029",
            "name": "getCivilianNamesOwn",
            "summary": "",
            "url": "namespaces/default.html#function_getCivilianNamesOwn"
        },                {
            "fqsen": "\\ncicGetNames\u0028\u0029",
            "name": "ncicGetNames",
            "summary": "",
            "url": "namespaces/default.html#function_ncicGetNames"
        },                {
            "fqsen": "\\ncicGetPlates\u0028\u0029",
            "name": "ncicGetPlates",
            "summary": "",
            "url": "namespaces/default.html#function_ncicGetPlates"
        },                {
            "fqsen": "\\delete_name\u0028\u0029",
            "name": "delete_name",
            "summary": "",
            "url": "namespaces/default.html#function_delete_name"
        },                {
            "fqsen": "\\delete_plate\u0028\u0029",
            "name": "delete_plate",
            "summary": "",
            "url": "namespaces/default.html#function_delete_plate"
        },                {
            "fqsen": "\\create_name\u0028\u0029",
            "name": "create_name",
            "summary": "",
            "url": "namespaces/default.html#function_create_name"
        },                {
            "fqsen": "\\create_plate\u0028\u0029",
            "name": "create_plate",
            "summary": "",
            "url": "namespaces/default.html#function_create_plate"
        },                {
            "fqsen": "\\create911Call\u0028\u0029",
            "name": "create911Call",
            "summary": "",
            "url": "namespaces/default.html#function_create911Call"
        },                {
            "fqsen": "\\edit_name\u0028\u0029",
            "name": "edit_name",
            "summary": "",
            "url": "namespaces/default.html#function_edit_name"
        },                {
            "fqsen": "\\edit_plate\u0028\u0029",
            "name": "edit_plate",
            "summary": "",
            "url": "namespaces/default.html#function_edit_plate"
        },                {
            "fqsen": "\\editnameid\u0028\u0029",
            "name": "editnameid",
            "summary": "",
            "url": "namespaces/default.html#function_editnameid"
        },                {
            "fqsen": "\\editplateid\u0028\u0029",
            "name": "editplateid",
            "summary": "",
            "url": "namespaces/default.html#function_editplateid"
        },                {
            "fqsen": "\\create_warrant\u0028\u0029",
            "name": "create_warrant",
            "summary": "",
            "url": "namespaces/default.html#function_create_warrant"
        },                {
            "fqsen": "\\ncicGetWarrants\u0028\u0029",
            "name": "ncicGetWarrants",
            "summary": "",
            "url": "namespaces/default.html#function_ncicGetWarrants"
        },                {
            "fqsen": "\\delete_warrant\u0028\u0029",
            "name": "delete_warrant",
            "summary": "",
            "url": "namespaces/default.html#function_delete_warrant"
        },                {
            "fqsen": "\\create_weapon\u0028\u0029",
            "name": "create_weapon",
            "summary": "",
            "url": "namespaces/default.html#function_create_weapon"
        },                {
            "fqsen": "\\ncicGetWeapons\u0028\u0029",
            "name": "ncicGetWeapons",
            "summary": "",
            "url": "namespaces/default.html#function_ncicGetWeapons"
        },                {
            "fqsen": "\\delete_weapon\u0028\u0029",
            "name": "delete_weapon",
            "summary": "",
            "url": "namespaces/default.html#function_delete_weapon"
        },                {
            "fqsen": "\\getNumberOfProfiles\u0028\u0029",
            "name": "getNumberOfProfiles",
            "summary": "",
            "url": "namespaces/default.html#function_getNumberOfProfiles"
        },                {
            "fqsen": "\\getNumberOfVehicles\u0028\u0029",
            "name": "getNumberOfVehicles",
            "summary": "",
            "url": "namespaces/default.html#function_getNumberOfVehicles"
        },                {
            "fqsen": "\\getNumberOfWeapons\u0028\u0029",
            "name": "getNumberOfWeapons",
            "summary": "",
            "url": "namespaces/default.html#function_getNumberOfWeapons"
        },                {
            "fqsen": "\\getCitationTypes\u0028\u0029",
            "name": "getCitationTypes",
            "summary": "",
            "url": "namespaces/default.html#function_getCitationTypes"
        },                {
            "fqsen": "\\getCitationTypeDetails\u0028\u0029",
            "name": "getCitationTypeDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getCitationTypeDetails"
        },                {
            "fqsen": "\\editCitationType\u0028\u0029",
            "name": "editCitationType",
            "summary": "",
            "url": "namespaces/default.html#function_editCitationType"
        },                {
            "fqsen": "\\deleteCitationType\u0028\u0029",
            "name": "deleteCitationType",
            "summary": "",
            "url": "namespaces/default.html#function_deleteCitationType"
        },                {
            "fqsen": "\\getDepartments\u0028\u0029",
            "name": "getDepartments",
            "summary": "",
            "url": "namespaces/default.html#function_getDepartments"
        },                {
            "fqsen": "\\getDepartmentDetails\u0028\u0029",
            "name": "getDepartmentDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getDepartmentDetails"
        },                {
            "fqsen": "\\editDepartment\u0028\u0029",
            "name": "editDepartment",
            "summary": "",
            "url": "namespaces/default.html#function_editDepartment"
        },                {
            "fqsen": "\\deleteDepartment\u0028\u0029",
            "name": "deleteDepartment",
            "summary": "",
            "url": "namespaces/default.html#function_deleteDepartment"
        },                {
            "fqsen": "\\getIncidentTypes\u0028\u0029",
            "name": "getIncidentTypes",
            "summary": "",
            "url": "namespaces/default.html#function_getIncidentTypes"
        },                {
            "fqsen": "\\getIncidentTypeDetails\u0028\u0029",
            "name": "getIncidentTypeDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getIncidentTypeDetails"
        },                {
            "fqsen": "\\editIncidentType\u0028\u0029",
            "name": "editIncidentType",
            "summary": "",
            "url": "namespaces/default.html#function_editIncidentType"
        },                {
            "fqsen": "\\deleteIncidentType\u0028\u0029",
            "name": "deleteIncidentType",
            "summary": "",
            "url": "namespaces/default.html#function_deleteIncidentType"
        },                {
            "fqsen": "\\getRadioCodes\u0028\u0029",
            "name": "getRadioCodes",
            "summary": "",
            "url": "namespaces/default.html#function_getRadioCodes"
        },                {
            "fqsen": "\\getRadioCodeDetails\u0028\u0029",
            "name": "getRadioCodeDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getRadioCodeDetails"
        },                {
            "fqsen": "\\editRadioCode\u0028\u0029",
            "name": "editRadioCode",
            "summary": "",
            "url": "namespaces/default.html#function_editRadioCode"
        },                {
            "fqsen": "\\deleteRadioCode\u0028\u0029",
            "name": "deleteRadioCode",
            "summary": "",
            "url": "namespaces/default.html#function_deleteRadioCode"
        },                {
            "fqsen": "\\getStreets\u0028\u0029",
            "name": "getStreets",
            "summary": "",
            "url": "namespaces/default.html#function_getStreets"
        },                {
            "fqsen": "\\getStreetDetails\u0028\u0029",
            "name": "getStreetDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getStreetDetails"
        },                {
            "fqsen": "\\editStreet\u0028\u0029",
            "name": "editStreet",
            "summary": "",
            "url": "namespaces/default.html#function_editStreet"
        },                {
            "fqsen": "\\deleteStreet\u0028\u0029",
            "name": "deleteStreet",
            "summary": "",
            "url": "namespaces/default.html#function_deleteStreet"
        },                {
            "fqsen": "\\getVehicles\u0028\u0029",
            "name": "getVehicles",
            "summary": "",
            "url": "namespaces/default.html#function_getVehicles"
        },                {
            "fqsen": "\\getVehicleDetails\u0028\u0029",
            "name": "getVehicleDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getVehicleDetails"
        },                {
            "fqsen": "\\editVehicle\u0028\u0029",
            "name": "editVehicle",
            "summary": "",
            "url": "namespaces/default.html#function_editVehicle"
        },                {
            "fqsen": "\\deleteVehicle\u0028\u0029",
            "name": "deleteVehicle",
            "summary": "",
            "url": "namespaces/default.html#function_deleteVehicle"
        },                {
            "fqsen": "\\getWarningTypes\u0028\u0029",
            "name": "getWarningTypes",
            "summary": "",
            "url": "namespaces/default.html#function_getWarningTypes"
        },                {
            "fqsen": "\\getWarningTypeDetails\u0028\u0029",
            "name": "getWarningTypeDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getWarningTypeDetails"
        },                {
            "fqsen": "\\editWarningType\u0028\u0029",
            "name": "editWarningType",
            "summary": "",
            "url": "namespaces/default.html#function_editWarningType"
        },                {
            "fqsen": "\\deleteWarningType\u0028\u0029",
            "name": "deleteWarningType",
            "summary": "",
            "url": "namespaces/default.html#function_deleteWarningType"
        },                {
            "fqsen": "\\getWarrantTypes\u0028\u0029",
            "name": "getWarrantTypes",
            "summary": "",
            "url": "namespaces/default.html#function_getWarrantTypes"
        },                {
            "fqsen": "\\getWarrantTypeDetails\u0028\u0029",
            "name": "getWarrantTypeDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getWarrantTypeDetails"
        },                {
            "fqsen": "\\editWarrantType\u0028\u0029",
            "name": "editWarrantType",
            "summary": "",
            "url": "namespaces/default.html#function_editWarrantType"
        },                {
            "fqsen": "\\deleteWarrantType\u0028\u0029",
            "name": "deleteWarrantType",
            "summary": "",
            "url": "namespaces/default.html#function_deleteWarrantType"
        },                {
            "fqsen": "\\getWeapons\u0028\u0029",
            "name": "getWeapons",
            "summary": "",
            "url": "namespaces/default.html#function_getWeapons"
        },                {
            "fqsen": "\\getWeaponDetails\u0028\u0029",
            "name": "getWeaponDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getWeaponDetails"
        },                {
            "fqsen": "\\editWeapon\u0028\u0029",
            "name": "editWeapon",
            "summary": "",
            "url": "namespaces/default.html#function_editWeapon"
        },                {
            "fqsen": "\\deleteWeapon\u0028\u0029",
            "name": "deleteWeapon",
            "summary": "",
            "url": "namespaces/default.html#function_deleteWeapon"
        },                {
            "fqsen": "\\resetData\u0028\u0029",
            "name": "resetData",
            "summary": "",
            "url": "namespaces/default.html#function_resetData"
        },                {
            "fqsen": "\\addNarrative\u0028\u0029",
            "name": "addNarrative",
            "summary": "",
            "url": "namespaces/default.html#function_addNarrative"
        },                {
            "fqsen": "\\assignUnit\u0028\u0029",
            "name": "assignUnit",
            "summary": "",
            "url": "namespaces/default.html#function_assignUnit"
        },                {
            "fqsen": "\\storeCall\u0028\u0029",
            "name": "storeCall",
            "summary": "",
            "url": "namespaces/default.html#function_storeCall"
        },                {
            "fqsen": "\\clearCall\u0028\u0029",
            "name": "clearCall",
            "summary": "",
            "url": "namespaces/default.html#function_clearCall"
        },                {
            "fqsen": "\\clearUnitFromCall\u0028\u0029",
            "name": "clearUnitFromCall",
            "summary": "",
            "url": "namespaces/default.html#function_clearUnitFromCall"
        },                {
            "fqsen": "\\freeUnitStatus\u0028\u0029",
            "name": "freeUnitStatus",
            "summary": "",
            "url": "namespaces/default.html#function_freeUnitStatus"
        },                {
            "fqsen": "\\newCall\u0028\u0029",
            "name": "newCall",
            "summary": "",
            "url": "namespaces/default.html#function_newCall"
        },                {
            "fqsen": "\\cadGetVehicleBOLOS\u0028\u0029",
            "name": "cadGetVehicleBOLOS",
            "summary": "",
            "url": "namespaces/default.html#function_cadGetVehicleBOLOS"
        },                {
            "fqsen": "\\cadGetPersonBOLOS\u0028\u0029",
            "name": "cadGetPersonBOLOS",
            "summary": "",
            "url": "namespaces/default.html#function_cadGetPersonBOLOS"
        },                {
            "fqsen": "\\create_citation\u0028\u0029",
            "name": "create_citation",
            "summary": "",
            "url": "namespaces/default.html#function_create_citation"
        },                {
            "fqsen": "\\create_warning\u0028\u0029",
            "name": "create_warning",
            "summary": "",
            "url": "namespaces/default.html#function_create_warning"
        },                {
            "fqsen": "\\delete_citation\u0028\u0029",
            "name": "delete_citation",
            "summary": "",
            "url": "namespaces/default.html#function_delete_citation"
        },                {
            "fqsen": "\\delete_arrest\u0028\u0029",
            "name": "delete_arrest",
            "summary": "",
            "url": "namespaces/default.html#function_delete_arrest"
        },                {
            "fqsen": "\\delete_warning\u0028\u0029",
            "name": "delete_warning",
            "summary": "",
            "url": "namespaces/default.html#function_delete_warning"
        },                {
            "fqsen": "\\ncicGetArrests\u0028\u0029",
            "name": "ncicGetArrests",
            "summary": "",
            "url": "namespaces/default.html#function_ncicGetArrests"
        },                {
            "fqsen": "\\ncicGetCitations\u0028\u0029",
            "name": "ncicGetCitations",
            "summary": "",
            "url": "namespaces/default.html#function_ncicGetCitations"
        },                {
            "fqsen": "\\ncicGetWarnings\u0028\u0029",
            "name": "ncicGetWarnings",
            "summary": "",
            "url": "namespaces/default.html#function_ncicGetWarnings"
        },                {
            "fqsen": "\\create_personbolo\u0028\u0029",
            "name": "create_personbolo",
            "summary": "",
            "url": "namespaces/default.html#function_create_personbolo"
        },                {
            "fqsen": "\\create_vehiclebolo\u0028\u0029",
            "name": "create_vehiclebolo",
            "summary": "",
            "url": "namespaces/default.html#function_create_vehiclebolo"
        },                {
            "fqsen": "\\delete_personbolo\u0028\u0029",
            "name": "delete_personbolo",
            "summary": "",
            "url": "namespaces/default.html#function_delete_personbolo"
        },                {
            "fqsen": "\\delete_vehiclebolo\u0028\u0029",
            "name": "delete_vehiclebolo",
            "summary": "",
            "url": "namespaces/default.html#function_delete_vehiclebolo"
        },                {
            "fqsen": "\\cadGetPersonBOLOSid\u0028\u0029",
            "name": "cadGetPersonBOLOSid",
            "summary": "",
            "url": "namespaces/default.html#function_cadGetPersonBOLOSid"
        },                {
            "fqsen": "\\cadGetVehicleBOLOSid\u0028\u0029",
            "name": "cadGetVehicleBOLOSid",
            "summary": "",
            "url": "namespaces/default.html#function_cadGetVehicleBOLOSid"
        },                {
            "fqsen": "\\changeaop\u0028\u0029",
            "name": "changeaop",
            "summary": "",
            "url": "namespaces/default.html#function_changeaop"
        },                {
            "fqsen": "\\editPersonBOLOS\u0028\u0029",
            "name": "editPersonBOLOS",
            "summary": "",
            "url": "namespaces/default.html#function_editPersonBOLOS"
        },                {
            "fqsen": "\\edit_vehiclebolo\u0028\u0029",
            "name": "edit_vehiclebolo",
            "summary": "",
            "url": "namespaces/default.html#function_edit_vehiclebolo"
        },                {
            "fqsen": "\\create_arrest\u0028\u0029",
            "name": "create_arrest",
            "summary": "",
            "url": "namespaces/default.html#function_create_arrest"
        },                {
            "fqsen": "\\quickStatus\u0028\u0029",
            "name": "quickStatus",
            "summary": "",
            "url": "namespaces/default.html#function_quickStatus"
        },                {
            "fqsen": "\\getMyCall\u0028\u0029",
            "name": "getMyCall",
            "summary": "",
            "url": "namespaces/default.html#function_getMyCall"
        },                {
            "fqsen": "\\checkTones\u0028\u0029",
            "name": "checkTones",
            "summary": "",
            "url": "namespaces/default.html#function_checkTones"
        },                {
            "fqsen": "\\setTone\u0028\u0029",
            "name": "setTone",
            "summary": "",
            "url": "namespaces/default.html#function_setTone"
        },                {
            "fqsen": "\\logoutUser\u0028\u0029",
            "name": "logoutUser",
            "summary": "",
            "url": "namespaces/default.html#function_logoutUser"
        },                {
            "fqsen": "\\changeStatus\u0028\u0029",
            "name": "changeStatus",
            "summary": "",
            "url": "namespaces/default.html#function_changeStatus"
        },                {
            "fqsen": "\\deleteDispatcher\u0028\u0029",
            "name": "deleteDispatcher",
            "summary": "",
            "url": "namespaces/default.html#function_deleteDispatcher"
        },                {
            "fqsen": "\\setDispatcher\u0028\u0029",
            "name": "setDispatcher",
            "summary": "",
            "url": "namespaces/default.html#function_setDispatcher"
        },                {
            "fqsen": "\\getAOP\u0028\u0029",
            "name": "getAOP",
            "summary": "",
            "url": "namespaces/default.html#function_getAOP"
        },                {
            "fqsen": "\\getDispatchers\u0028\u0029",
            "name": "getDispatchers",
            "summary": "",
            "url": "namespaces/default.html#function_getDispatchers"
        },                {
            "fqsen": "\\getDispatchersMDT\u0028\u0029",
            "name": "getDispatchersMDT",
            "summary": "",
            "url": "namespaces/default.html#function_getDispatchersMDT"
        },                {
            "fqsen": "\\setUnitActive\u0028\u0029",
            "name": "setUnitActive",
            "summary": "",
            "url": "namespaces/default.html#function_setUnitActive"
        },                {
            "fqsen": "\\getAvailableUnits\u0028\u0029",
            "name": "getAvailableUnits",
            "summary": "",
            "url": "namespaces/default.html#function_getAvailableUnits"
        },                {
            "fqsen": "\\getUnAvailableUnits\u0028\u0029",
            "name": "getUnAvailableUnits",
            "summary": "",
            "url": "namespaces/default.html#function_getUnAvailableUnits"
        },                {
            "fqsen": "\\getIndividualStatus\u0028\u0029",
            "name": "getIndividualStatus",
            "summary": "",
            "url": "namespaces/default.html#function_getIndividualStatus"
        },                {
            "fqsen": "\\getIncidentType\u0028\u0029",
            "name": "getIncidentType",
            "summary": "",
            "url": "namespaces/default.html#function_getIncidentType"
        },                {
            "fqsen": "\\getStreet\u0028\u0029",
            "name": "getStreet",
            "summary": "",
            "url": "namespaces/default.html#function_getStreet"
        },                {
            "fqsen": "\\getActiveUnits\u0028\u0029",
            "name": "getActiveUnits",
            "summary": "",
            "url": "namespaces/default.html#function_getActiveUnits"
        },                {
            "fqsen": "\\getActiveUnitsModal\u0028\u0029",
            "name": "getActiveUnitsModal",
            "summary": "",
            "url": "namespaces/default.html#function_getActiveUnitsModal"
        },                {
            "fqsen": "\\getActiveCalls\u0028\u0029",
            "name": "getActiveCalls",
            "summary": "",
            "url": "namespaces/default.html#function_getActiveCalls"
        },                {
            "fqsen": "\\getActivePersonBOLO\u0028\u0029",
            "name": "getActivePersonBOLO",
            "summary": "",
            "url": "namespaces/default.html#function_getActivePersonBOLO"
        },                {
            "fqsen": "\\getUnitsOnCall\u0028\u0029",
            "name": "getUnitsOnCall",
            "summary": "",
            "url": "namespaces/default.html#function_getUnitsOnCall"
        },                {
            "fqsen": "\\getCallDetails\u0028\u0029",
            "name": "getCallDetails",
            "summary": "",
            "url": "namespaces/default.html#function_getCallDetails"
        },                {
            "fqsen": "\\getCivilianNamesOption\u0028\u0029",
            "name": "getCivilianNamesOption",
            "summary": "",
            "url": "namespaces/default.html#function_getCivilianNamesOption"
        },                {
            "fqsen": "\\getCitations\u0028\u0029",
            "name": "getCitations",
            "summary": "",
            "url": "namespaces/default.html#function_getCitations"
        },                {
            "fqsen": "\\getVehicleMakes\u0028\u0029",
            "name": "getVehicleMakes",
            "summary": "",
            "url": "namespaces/default.html#function_getVehicleMakes"
        },                {
            "fqsen": "\\getVehicleModels\u0028\u0029",
            "name": "getVehicleModels",
            "summary": "",
            "url": "namespaces/default.html#function_getVehicleModels"
        },                {
            "fqsen": "\\getVehicle\u0028\u0029",
            "name": "getVehicle",
            "summary": "",
            "url": "namespaces/default.html#function_getVehicle"
        },                {
            "fqsen": "\\getColors\u0028\u0029",
            "name": "getColors",
            "summary": "",
            "url": "namespaces/default.html#function_getColors"
        },                {
            "fqsen": "\\getCivilianNames\u0028\u0029",
            "name": "getCivilianNames",
            "summary": "",
            "url": "namespaces/default.html#function_getCivilianNames"
        },                {
            "fqsen": "\\callCheck\u0028\u0029",
            "name": "callCheck",
            "summary": "",
            "url": "namespaces/default.html#function_callCheck"
        },                {
            "fqsen": "\\rms_warnings\u0028\u0029",
            "name": "rms_warnings",
            "summary": "",
            "url": "namespaces/default.html#function_rms_warnings"
        },                {
            "fqsen": "\\rms_citations\u0028\u0029",
            "name": "rms_citations",
            "summary": "",
            "url": "namespaces/default.html#function_rms_citations"
        },                {
            "fqsen": "\\rms_arrests\u0028\u0029",
            "name": "rms_arrests",
            "summary": "",
            "url": "namespaces/default.html#function_rms_arrests"
        },                {
            "fqsen": "\\rms_warrants\u0028\u0029",
            "name": "rms_warrants",
            "summary": "",
            "url": "namespaces/default.html#function_rms_warrants"
        },                {
            "fqsen": "\\logoutResponder\u0028\u0029",
            "name": "logoutResponder",
            "summary": "",
            "url": "namespaces/default.html#function_logoutResponder"
        },                {
            "fqsen": "\\name\u0028\u0029",
            "name": "name",
            "summary": "",
            "url": "namespaces/default.html#function_name"
        },                {
            "fqsen": "\\plate\u0028\u0029",
            "name": "plate",
            "summary": "",
            "url": "namespaces/default.html#function_plate"
        },                {
            "fqsen": "\\weapon\u0028\u0029",
            "name": "weapon",
            "summary": "",
            "url": "namespaces/default.html#function_weapon"
        },                {
            "fqsen": "\\rejectRequest\u0028\u0029",
            "name": "rejectRequest",
            "summary": "",
            "url": "namespaces/default.html#function_rejectRequest"
        },                {
            "fqsen": "\\getIdentityRequests\u0028\u0029",
            "name": "getIdentityRequests",
            "summary": "",
            "url": "namespaces/default.html#function_getIdentityRequests"
        },                {
            "fqsen": "\\getUserList\u0028\u0029",
            "name": "getUserList",
            "summary": "",
            "url": "namespaces/default.html#function_getUserList"
        },                {
            "fqsen": "\\updateProfile\u0028\u0029",
            "name": "updateProfile",
            "summary": "",
            "url": "namespaces/default.html#function_updateProfile"
        },                {
            "fqsen": "\\getMyRank\u0028\u0029",
            "name": "getMyRank",
            "summary": "",
            "url": "namespaces/default.html#function_getMyRank"
        },                {
            "fqsen": "\\changePassword\u0028\u0029",
            "name": "changePassword",
            "summary": "",
            "url": "namespaces/default.html#function_changePassword"
        },                {
            "fqsen": "\\getAgencies\u0028\u0029",
            "name": "getAgencies",
            "summary": "",
            "url": "namespaces/default.html#function_getAgencies"
        },                {
            "fqsen": "\\getAgenciesWarrants\u0028\u0029",
            "name": "getAgenciesWarrants",
            "summary": "",
            "url": "namespaces/default.html#function_getAgenciesWarrants"
        },                {
            "fqsen": "\\getLicenseStatuses\u0028\u0029",
            "name": "getLicenseStatuses",
            "summary": "",
            "url": "namespaces/default.html#function_getLicenseStatuses"
        },                {
            "fqsen": "\\getLicenseTypes\u0028\u0029",
            "name": "getLicenseTypes",
            "summary": "",
            "url": "namespaces/default.html#function_getLicenseTypes"
        },                {
            "fqsen": "\\getLicenseClasses\u0028\u0029",
            "name": "getLicenseClasses",
            "summary": "",
            "url": "namespaces/default.html#function_getLicenseClasses"
        },                {
            "fqsen": "\\getLicenseIssuers\u0028\u0029",
            "name": "getLicenseIssuers",
            "summary": "",
            "url": "namespaces/default.html#function_getLicenseIssuers"
        },                {
            "fqsen": "\\getPlateRegisrars\u0028\u0029",
            "name": "getPlateRegisrars",
            "summary": "",
            "url": "namespaces/default.html#function_getPlateRegisrars"
        },                {
            "fqsen": "\\getGenders\u0028\u0029",
            "name": "getGenders",
            "summary": "",
            "url": "namespaces/default.html#function_getGenders"
        },                {
            "fqsen": "\\getRaces\u0028\u0029",
            "name": "getRaces",
            "summary": "",
            "url": "namespaces/default.html#function_getRaces"
        },                {
            "fqsen": "\\getData2\u0028\u0029",
            "name": "getData2",
            "summary": "",
            "url": "namespaces/default.html#function_getData2"
        },                {
            "fqsen": "\\getData3\u0028\u0029",
            "name": "getData3",
            "summary": "",
            "url": "namespaces/default.html#function_getData3"
        },                {
            "fqsen": "\\getDataSetTable\u0028\u0029",
            "name": "getDataSetTable",
            "summary": "",
            "url": "namespaces/default.html#function_getDataSetTable"
        },                {
            "fqsen": "\\register\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "namespaces/default.html#function_register"
        },                {
            "fqsen": "\\civreg\u0028\u0029",
            "name": "civreg",
            "summary": "",
            "url": "namespaces/default.html#function_civreg"
        },                {
            "fqsen": "\\updateCallsign\u0028\u0029",
            "name": "updateCallsign",
            "summary": "",
            "url": "namespaces/default.html#function_updateCallsign"
        },                {
            "fqsen": "\\getStatus\u0028\u0029",
            "name": "getStatus",
            "summary": "",
            "url": "namespaces/default.html#function_getStatus"
        },                {
            "fqsen": "\\mdtGetVehicleBOLOS\u0028\u0029",
            "name": "mdtGetVehicleBOLOS",
            "summary": "",
            "url": "namespaces/default.html#function_mdtGetVehicleBOLOS"
        },                {
            "fqsen": "\\mdtGetPersonBOLOS\u0028\u0029",
            "name": "mdtGetPersonBOLOS",
            "summary": "",
            "url": "namespaces/default.html#function_mdtGetPersonBOLOS"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
